gb_lesson1_djgo/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),
    #
    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),
    #
    path('products/create/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/', adminapp.ProductListView.as_view(), name='products'),
    path('products/read/category/<int:pk>/', adminapp.ProductListView.as_view(), name='products_by_category'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

gb_lesson1_djgo/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/', authapp.edit, name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

gb_lesson1_djgo/gb_lesson1_djgo/urls.py
from django.contrib import admin
from django.urls import path, re_path
import mainapp.views as mainapp
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    re_path(r'^products/(?P<pk>\d+)/$', mainapp.products, name='category'),
    path('contacts', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls, name='admin'),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gb_lesson1_djgo/adminapp/models.py
from django.db import models

# Create your models here.

gb_lesson1_djgo/adminapp/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.views.generic.list import ListView
from mainapp.models import ProductCategory, Product
from authapp.models import ShopUser
from django.shortcuts import render


class IsSuperUserVies(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


class ProductListView(IsSuperUserVies, ListView):
    model = Product
    template_name = 'adminapp/products.html'

    def get_queryset(self):
        qs = super(ProductListView, self).get_queryset()
        category_pk = self.kwargs.get('pk')
        if category_pk:
            return qs.filter(category__pk=category_pk)
        else:
            return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['title'] = "Админка. Продукты"
        context['category_menu'] = ProductCategory.objects.all()
        return context


class ProductDetailView(IsSuperUserVies, DetailView):
    model = Product
    template_name = 'adminapp/product.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['title'] = "Админка. {}".format(context['product'])
        context['category_menu'] = ProductCategory.objects.all()
        return context


class ProductUpdateView(IsSuperUserVies, UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    fields = ('name', 'short_desc')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Админка. Редактирование продукта'
        context['category_menu'] = ProductCategory.objects.all()
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:product_read', kwargs={'pk': self.kwargs.get('pk')})


class ProductCreateView(IsSuperUserVies, CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('admin_custom:products')


class ProductDeleteView(IsSuperUserVies, DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        return reverse_lazy('admin_custom:products')


# ----------------CATEGORIES----------------
class CategoryListView(IsSuperUserVies, ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['title'] = 'Админка. Категории'
        return context


class CategoryUpdateView(IsSuperUserVies, UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    fields = ('name', 'description')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Админка. Редактирование категории'
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:categories')


class CategoryCreateView(IsSuperUserVies, CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('admin_custom:categories')


class CategoryDeleteView(IsSuperUserVies, DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'

    def get_success_url(self):
        return reverse_lazy('admin_custom:categories')


# ----------------USERS----------------
class UserListView(IsSuperUserVies, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['title'] = 'Админка. Пользователи'
        return context


class UserUpdateView(IsSuperUserVies, UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    fields = 'first_name', 'last_name', 'email',

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Админка. Редактирование пользователя'
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:users')


class UserCreateView(IsSuperUserVies, CreateView):
    model = ShopUser
    template_name = 'adminapp/user_create.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('admin_custom:users')


class UserDeleteView(IsSuperUserVies, DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Админка. Удаление пользователя'
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:users')

    # def delete(self, request, *args, **kwargs):
    #     deleted_user = super(UserDeleteView, self).delete(**kwargs)
    #     print(deleted_user)
    def delete(self, request, *args, **kwargs):
        deleted_user = self.get_object()
        deleted_user.is_active = False
        deleted_user.save()
        return HttpResponseRedirect(self.get_success_url())

gb_lesson1_djgo/adminapp/templates/adminapp/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h1>Доступные категории:</h1>
<ul>
    {% for object in object_list %}
        <a href="{% url 'admin_custom:category_update' object.pk %}">{{ object.name }}</a>
    {% endfor %}
</ul>
<h1>Создание категории:</h1>
<a href="{% url 'admin_custom:category_create' %}">Создать категорию</a>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/category_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="category_delete">
        Уверены, что хотите удалить {{ object.name }}?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_custom:categories' %}">
                Отмена
            </a>
        </button>
    </div>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/category_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<form class="form_category_update" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Применить">
    <a href="{% url 'admin_custom:category_delete' object.pk %}">Удалить категорию</a>
    <br>
    <br>
    <a href="{% url 'admin_custom:categories' %}">Назад</a>
</form>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/product.html
{% load custom_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
{% include 'adminapp/includes/inc_category_menu.html' %}
<h1>{{ object.name }}</h1>
<img src='{{ object.image|image_clear_dots }}' height="250px">
<p>{{ object.short_desc }}</p>
<br>
<a href="{% url 'admin_custom:product_update' object.pk %}">Редактировать</a>
<br>
<a href="{% url 'adminapp:product_delete' object.pk %}">Удалить продукт</a>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/product_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="product_delete">
        Уверены, что хотите удалить {{ object.name }}?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_custom:products' %}">
                Отмена
            </a>
        </button>
    </div>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/product_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<form class="form_product_update" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Применить">
</form>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
{% include 'adminapp/includes/inc_category_menu.html' %}
<a href="{% url 'adminapp:product_create' %}">Создать продукт</a>
<ul>
    {% for object in object_list %}
        <a href="{% url 'admin_custom:product_read' object.pk %}">{{ object.name }}</a>
    {% endfor %}
</ul>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/user_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h1>Создание пользователя:</h1>
<form class="form_user_update" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Создать">
    <br>
    <a href="{% url 'admin_custom:users' %}">Назад</a>
</form>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/user_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <div class="category_delete">
        Уверены, что хотите удалить {{ object.username }}?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_custom:users' %}">
                Отмена
            </a>
        </button>
    </div>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/user_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h1>Редактирование пользователя: {{ object.username }}</h1>
<form class="form_user_update" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Применить">
    <a href="{% url 'admin_custom:user_delete' object.pk %}">Удалить пользователя</a>
    <br>
    <br>
    <a href="{% url 'admin_custom:users' %}">Назад</a>
</form>
</body>
</html>

gb_lesson1_djgo/adminapp/templates/adminapp/users.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
<h1>Пользователи в системе:</h1>
<ul>
    {% for object in object_list %}
        <li class="user_li">
            <div class="user_info">
                <a href="{% url 'admin_custom:user_update' object.pk %}">{{ object.username }}</a>
                {% if not object.is_active %}
                    <p>&nbsp;- не активен</p>
                {% endif %}
            </div>
        </li>
    {% endfor %}
</ul>
<h1 style="clear: both">Создать пользователя:</h1>
<a href="{% url 'admin_custom:user_create' %}">Создать</a>
</body>
</html>