gb_lesson1_djgo/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/', authapp.edit, name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

gb_lesson1_djgo/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
   path('', basketapp.basket, name='read'),
   path('add/product/<int:pk>/', basketapp.add, name='add'),
   path('delete/product/<int:pk>/', basketapp.delete, name='delete'),
   path('edit/<int:pk>/', basketapp.edit, name='basket_edit'),
]

gb_lesson1_djgo/gb_lesson1_djgo/urls.py
from django.contrib import admin
from django.urls import path, re_path
import mainapp.views as mainapp
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    re_path(r'^products/(?P<pk>\d+)/$', mainapp.products, name='category'),
    path('contacts', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls, name='admin'),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gb_lesson1_djgo/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('detail/<int:pk>/', mainapp.detail, name='detail'),
   path('<int:pk>/', mainapp.products, name='category'),
]

gb_lesson1_djgo/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name='Имя категории', max_length=255, unique=True)
    description = models.TextField(verbose_name='Описание категории', blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    category = models.ForeignKey(ProductCategory, verbose_name='Имя категории товара', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_hot = models.BooleanField(verbose_name='горячее предложение', default=False)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

gb_lesson1_djgo/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory

# Create your views here.
links_menu = [
    {'href': 'main', 'name': 'Главная'},
    {'href': 'products:index', 'name': 'Продукты'},
    {'href': 'contacts', 'name': 'Контакты'},
    {'href': 'basket:read', 'name': 'Корзина'},
]


def main(request):
    context = {"links_menu": links_menu, 'empty_array': [], 'array': [number for number in range(1, 6)]}
    return render(request, 'mainapp/index.html', context)


def detail(request, pk=None):
    category_menu = ProductCategory.objects.all()

    detail_product = get_object_or_404(Product, pk=pk)
    context = {
        "links_menu": links_menu,
        "category_menu": category_menu,
        "detail_product": detail_product,
    }
    return render(request, 'mainapp/detail.html', context)


def products(request, pk=None):
    category_menu = ProductCategory.objects.all()

    if pk or pk == 0:
        filter_products = Product.objects.all()
        if pk:
            filter_products = Product.objects.filter(category=pk)
        context = {
            "links_menu": links_menu,
            "category_menu": category_menu,
            "products": filter_products
        }
        return render(request, 'mainapp/products.html', context)
    else:
        hot_product = Product.objects.filter(is_hot=True).first()
        context = {
            "links_menu": links_menu,
            "category_menu": category_menu,
            "hot_product": hot_product
        }
        return render(request, 'mainapp/hot_product.html', context)


def contacts(request):
    context = {"links_menu": links_menu}
    return render(request, 'mainapp/contacts.html', context)

gb_lesson1_djgo/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <style>
        .header { background-image: url({% static 'img/fon.jpg' %}); }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
           <div class="logo">
                <a href="{% url 'main' %}"><img src="{% static 'img/logo.png' %}" height="70px" alt="MainLogo"></a>
            </div>
            {% include 'mainapp/includes/inc_menu.html' %}
            <hr>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

gb_lesson1_djgo/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Контакты</title>
{% endblock %}

{% block content %}
    <h1>Контакты</h1>
{% endblock %}

gb_lesson1_djgo/mainapp/templates/mainapp/detail.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>{{ detail_product.name }}</title>
{% endblock %}

{% block content %}
    <h1>Продукты</h1>
    <p>Продуктов в корзине: {{ request.user|basket_total_quantity }} </p>
    <p>На общую сумму {{ request.user|basket_total_cost }} рублей</p>
    {% include 'mainapp/includes/inc_categories_menu.html' %}
    <div class="product_info">
        <h3>{{ detail_product.name }}</h3>
        <img src='{{ detail_product.image.url }}' height="250px">
        <div class="short_desc">{{ detail_product.short_desc }}</div>
        <br>
        <br>
        <a href="{% url 'basket:add' detail_product.pk %}">Добавить в корзину</a>
        <br>
        <a href="{% url 'basket:delete' detail_product.pk %}">Удалить из корзины</a>
        <br>
        <br>
    </div>
{% endblock %}

gb_lesson1_djgo/mainapp/templates/mainapp/hot_product.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content %}
    <h1>Продукты</h1>
    <p>Продуктов в корзине: {{ request.user|basket_total_quantity }} </p>
    <p>На общую сумму {{ request.user|basket_total_cost }} рублей</p>
    {% include 'mainapp/includes/inc_categories_menu.html' %}
    <div class="catalog">
        <div class="item">
            <h3>{{ hot_product.name }}</h3>
            <img src='{{ hot_product.image.url }}' height="150px">
            <div class="short_desc">{{ hot_product.short_desc }}</div>
            <h1 style="color: red;">Горячее предложение</h1>
            <a href="{% url 'mainapp:detail' hot_product.pk %}">Просмотреть товар</a>
        </div>
    </div>
{% endblock %}

gb_lesson1_djgo/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Главная</title>
{% endblock %}

{% block content %}
    <h1 class="index">Главная</h1>
    {% if request.user.username %}
        <div>Привет, {{ request.user.username|title }}!</div>
    {% else %}
        <div>Привет, незнакомец!</div>
    {% endif %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'auth:edit' %}">Изменить данные</a> или <a href="{% url 'auth:logout' %}">Выйти</a>
    {% else %}
        <a href="{% url 'auth:login' %}">Войти</a> или <a href="{% url 'auth:register' %}">Зарегистрироваться</a>
    {% endif %}
    <div>Сегодня у нас: {% now 'd/m/Y' %}</div>
    {% if empty_array %}
        <h1>{{ array.0 }}</h1>
    {% else %}
        <h1>Передан пустой массив</h1>
    {% endif %}
    {% for element in array %}
        <h1>{{ element }}</h1>
    {% endfor %}
{% endblock %}

gb_lesson1_djgo/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content %}
    <h1>Продукты</h1>
    <p>Продуктов в корзине: {{ basket_quantity }} </p>
    <p>На общую сумму {{ total_price }} рублей</p>
    {% include 'mainapp/includes/inc_categories_menu.html' %}
    <div class="catalog">
        {% for product in products %}
            <div class="item">
                <h3>{{ product.name }}</h3>
                <img src='{{ product.image.url }}' height="150px">
                <div class="short_desc">{{ product.short_desc }}</div>
                <a href="{% url 'basket:add' product.pk %}">Добавить в корзину</a>
                <br>
                <a href="{% url 'basket:delete' product.pk %}">Удалить из корзины</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}